// ==========================================
// Events & Tournaments Module
// ==========================================

// Uses shared global state declared in index.html:
// tournamentRosterCache
// tournamentRosterFilter

async function createTournamentV90(){
  const uiType=el('tmType').value;
  const backendType=uiType==='INTERNATIONAL'?'ABROAD':uiType;
  const r=await sb.rpc('tournament_manager_save_v90',{
    p_id:null,p_name:el('tmName').value.trim(),p_type:backendType,
    p_destination_country:uiType==='INTERNATIONAL'?el('tmCountry').value.trim():null,
    p_city:el('tmCity').value.trim()||null,p_venue:el('tmVenue').value.trim(),
    p_start_date:el('tmStart').value||null,p_end_date:el('tmEnd').value||null,
    p_registration_deadline:el('tmDeadline').value?new Date(el('tmDeadline').value).toISOString():null,
    p_reporting_time:el('tmReporting').value||null,p_maps_url:el('tmMaps').value.trim()||null,
    p_player_fee_aed:Number(el('tmFee').value||0),p_max_players:el('tmMax').value?Number(el('tmMax').value):null,
    p_information:el('tmInfo').value.trim()||null,p_status:'OPEN'
  });
  if(r.error)return showMsg('globalMsg',r.error.message,'error');
  showMsg('globalMsg','Tournament created. It is automatically published in Upcoming Activities & Events.');
  ['tmName','tmCountry','tmCity','tmVenue','tmStart','tmEnd','tmDeadline','tmReporting','tmMaps','tmMax','tmInfo']
    .forEach(x=>{if(el(x))el(x).value=''});
  el('tmFee').value='0';
  await loadTournamentManagerV90();
  await loadHomeEventsV91();
}
async function loadHomeEventsV91(){const b=el('homeUpcomingEvents');if(!b)return;const r=await sb.rpc('public_upcoming_events_v91');if(r.error){b.innerHTML='<div class="muted">Upcoming activities are temporarily unavailable.</div>';return}const rows=r.data||[];b.innerHTML=rows.length?rows.slice(0,3).map(x=>`<div class="training"><span class="pill">${esc(x.category)}</span><strong> ${esc(x.title)}</strong><br><span class="muted">${new Date(x.start_date+'T12:00').toLocaleDateString()}${x.end_date&&x.end_date!==x.start_date?' → '+new Date(x.end_date+'T12:00').toLocaleDateString():''}${x.location?' · '+esc(x.location):''}</span>${x.description?`<p class="small">${esc(x.description)}</p>`:''}</div>`).join(''):'<div class="muted">No upcoming activities published.</div>'}
async function saveEventV91(){const r=await sb.rpc('management_save_event_v91',{p_id:null,p_title:el('evTitle').value.trim(),p_category:el('evCategory').value,p_start_date:el('evStart').value||null,p_end_date:el('evEnd').value||el('evStart').value||null,p_location:el('evLocation').value.trim()||null,p_description:el('evDescription').value.trim()||null,p_published:el('evPublished').checked});if(r.error)return showMsg('globalMsg',r.error.message,'error');showMsg('globalMsg','Event saved.');await loadEventsManagerV91();await loadHomeEventsV91()}
async function loadEventsManagerV91(){const b=el('eventsManagerList');if(!b)return;const r=await sb.rpc('management_list_events_v91');if(r.error){b.innerHTML=`<div class="notice error">${esc(r.error.message)}</div>`;return}b.innerHTML=(r.data||[]).map(x=>`<div class="training"><strong>${esc(x.title)}</strong> · <span class="pill">${esc(x.category)}</span><br><span class="muted">${x.start_date}${x.location?' · '+esc(x.location):''} · ${x.published?'PUBLISHED':'UNPUBLISHED'}</span><br><button class="secondary" onclick="toggleEventV91('${x.id}',${!x.published})">${x.published?'UNPUBLISH':'PUBLISH'}</button></div>`).join('')||'<div class="muted">No events.</div>'}
async function toggleEventV91(id,published){const r=await sb.rpc('management_set_event_published_v91',{p_id:id,p_published:published});if(r.error)return showMsg('globalMsg',r.error.message,'error');await loadEventsManagerV91();await loadHomeEventsV91()}
function toggleTournamentDestination(){el('tmCountryWrap')?.classList.toggle('hidden',el('tmType')?.value!=='INTERNATIONAL')}
async function loadPlayerTournamentsV90(){const box=el('playerTournaments');if(!box)return;const r=await sb.rpc('tournament_list_for_player_v90');if(r.error){box.innerHTML=`<div class="muted">${esc(r.error.message)}</div>`;return}const rows=r.data||[];box.innerHTML=rows.length?rows.map(t=>{const closed=t.status!=='OPEN'||new Date(t.registration_deadline)<=new Date();const visa=t.visa_result?`<div class="notice ${t.visa_result==='VISA REQUIRED'?'warn':''}"><strong>${esc(t.visa_result)}</strong><br><span class="small">Visa and entry compliance remain the player's responsibility. Requirements may change; verify before travel.</span></div>`:'';return `<div class="tournamentCard"><div class="tournamentTop"><div><span class="pill">${esc(t.tournament_type)}</span><h3>${esc(t.name)}</h3></div><span class="pill">${esc(t.status)}</span></div><div class="muted">${esc(t.venue)}${t.city?' · '+esc(t.city):''}${t.destination_country?' · '+esc(t.destination_country):''}<br>${new Date(t.start_date+'T12:00').toLocaleDateString()}${t.end_date!==t.start_date?' → '+new Date(t.end_date+'T12:00').toLocaleDateString():''}<br>Registration deadline: ${new Date(t.registration_deadline).toLocaleString()}</div>${t.information?`<p>${esc(t.information)}</p>`:''}${visa}<div class="plan"><strong>YOUR AVAILABILITY: ${esc(t.availability||'NO RESPONSE')}</strong>${t.selection_status&&t.selection_status!=='PENDING'?` · <span class="pill">${esc(t.selection_status)}</span>`:''}<textarea id="tNote-${t.id}" placeholder="Optional note to Coach">${esc(t.player_note||'')}</textarea>${closed?'<span class="pill">REGISTRATION CLOSED</span>':`<button class="green" onclick="setTournamentAvailabilityV90('${t.id}','AVAILABLE')">AVAILABLE</button><button class="secondary" onclick="setTournamentAvailabilityV90('${t.id}','NOT_AVAILABLE')">NOT AVAILABLE</button>`}</div></div>`}).join(''):'<div class="muted">No tournaments available.</div>'}
async function setTournamentAvailabilityV90(id,a){const r=await sb.rpc('tournament_set_availability_v90',{p_tournament_id:id,p_availability:a,p_note:el('tNote-'+id)?.value.trim()||null});if(r.error)return showMsg('globalMsg',r.error.message,'error');showMsg('globalMsg','Tournament availability saved.');await loadPlayerTournamentsV90()}
async function loadTournamentManagerV90(){const box=el('tournamentManagerList');if(!box)return;const r=await sb.rpc('tournament_manager_list_v90');if(r.error){box.innerHTML=`<div class="muted">${esc(r.error.message)}</div>`;return}const rows=r.data||[];box.innerHTML=rows.length?rows.map(t=>`<div class="tournamentCard"><div class="tournamentTop"><div><span class="pill">${esc(t.tournament_type)}</span><strong> ${esc(t.name)}</strong></div><span class="pill">${esc(t.status)}</span></div><div class="muted">${esc(t.venue)} · ${new Date(t.start_date+'T12:00').toLocaleDateString()}${t.end_date!==t.start_date?' → '+new Date(t.end_date+'T12:00').toLocaleDateString():''}<br>Deadline: ${new Date(t.registration_deadline).toLocaleString()}</div><div class="merchStatusRow"><span class="pill">${t.available_count} AVAILABLE</span><span class="pill">${t.not_available_count} NOT AVAILABLE</span><span class="pill">${t.no_response_count} NO RESPONSE</span><button onclick="loadTournamentRosterV90('${t.id}','${esc(t.name).replaceAll("'","&#39;")}')">VIEW PLAYERS</button></div></div>`).join(''):'<div class="muted">No tournaments.</div>'}
async function loadTournamentRosterV90(id,name){const r=await sb.rpc('tournament_manager_roster_v90',{p_tournament_id:id});if(r.error)return showMsg('globalMsg',r.error.message,'error');tournamentRosterCache=r.data||[];tournamentRosterFilter='ALL';el('tournamentRosterCard').classList.remove('hidden');el('tournamentRosterTitle').textContent=name;el('tournamentRosterCard').dataset.tournamentId=id;el('tournamentRosterCard').dataset.tournamentName=name;renderTournamentRosterV91()}
function filterTournamentRosterV91(f){tournamentRosterFilter=f;renderTournamentRosterV91()}
function renderTournamentRosterV91(){const rows=tournamentRosterCache||[];const av=rows.filter(x=>x.availability==='AVAILABLE').length,na=rows.filter(x=>x.availability==='NOT_AVAILABLE').length,nr=rows.length-av-na,sel=rows.filter(x=>x.selection_status==='SELECTED').length;el('tournamentRosterSummary').innerHTML=`<span class="pill">${av} AVAILABLE</span><span class="pill">${na} NOT AVAILABLE</span><span class="pill">${nr} NO RESPONSE</span><span class="pill ok">${sel} SELECTED</span>`;const show=rows.filter(p=>tournamentRosterFilter==='ALL'||(tournamentRosterFilter==='NO_RESPONSE'?!p.availability:p.availability===tournamentRosterFilter));const tid=el('tournamentRosterCard').dataset.tournamentId,name=el('tournamentRosterCard').dataset.tournamentName;el('tournamentRoster').innerHTML=show.map(p=>`<div class="tournamentRosterRow"><div><strong>${esc(p.full_name)}</strong><br><span class="small">${esc(p.position||'—')} · ${esc(p.nationality||'Nationality missing')}</span></div><div>${esc(p.availability||'NO RESPONSE')}</div><div>${p.visa_result?esc(p.visa_result):'—'}</div><div>${esc(p.selection_status||'PENDING')}</div><div>${p.availability==='AVAILABLE'?`<button onclick="selectTournamentPlayerV90('${tid}','${p.player_id}','SELECTED','${esc(name).replaceAll("'","&#39;")}')">SELECT</button><button class="secondary" onclick="selectTournamentPlayerV90('${tid}','${p.player_id}','NOT_SELECTED','${esc(name).replaceAll("'","&#39;")}')">NOT SELECTED</button>`:'—'}</div></div>`).join('')||'<div class="muted">No players in this filter.</div>';const final=rows.filter(x=>x.selection_status==='SELECTED');el('tournamentFinalSquad').innerHTML=final.length?final.sort((a,b)=>(a.position||'').localeCompare(b.position||'')).map(p=>`<div class="training"><strong>${esc(p.full_name)}</strong> · ${esc(p.position||'Not Assigned')}</div>`).join(''):'<div class="muted">No players selected yet.</div>'}
async function selectTournamentPlayerV90(tid,pid,status,name){const r=await sb.rpc('tournament_manager_select_player_v90',{p_tournament_id:tid,p_player_id:pid,p_selection:status});if(r.error)return showMsg('globalMsg',r.error.message,'error');await loadTournamentRosterV90(tid,name)}
